name: panfleto_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.0
  provider: ^6.1.2
  json_annotation: ^4.8.1
  http: ^1.2.2
  intl: ^0.18.0
  location: ^7.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.3.3
  geolocator: ^13.0.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
